# Generated by Django 5.0.4 on 2024-04-23 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificnamemodel',
            name='genus',
        ),
        migrations.AddField(
            model_name='scientificnamemodel',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filters.genusmodel'),
        ),
    ]
